-- Edited by maki

if vim.g.colors_name ~= nil then
	vim.cmd 'highlight clear'
end
vim.g.colors_name = 'catppuccin-mocha'

-- Highlight groups
local hi = vim.api.nvim_set_hl

local colors = {
	red = '#f38ba9',
	blue = '#89b4fb',
	beige = '#f2cdce',
	yellow = '#f9e2b0',
	green = '#a6e3a2',
	purple = '#cba6f8',
	orange = '#fab388',
	teal = '#94e2d6',
	cyan = '#89dcec',
	lavender = '#b4beff',
	rose = '#eba0ad',
	background = '#000000',
	white = '#cdd6f5',
}

-- Added highlights
hi(0, '@lsp.type.concept', { fg = colors.orange })
hi(0, '@lsp.mod.readonly', { italic = true })
-- special for rust
hi(0, '@lsp.typemod.variable.mutable.rust', { fg = colors.white, bold = true })
hi(0, '@lsp.typemod.keyword.async.rust', { italic = true })
hi(0, '@lsp.type.macro.rust', { fg = colors.red })

hi(0, '@attribute', { link = 'Constant' })
hi(0, '@character.special', { link = 'SpecialChar' })
hi(0, '@comment.documentation', { link = 'Comment' })
hi(0, '@comment.error', { bg = '#f38ba9', fg = colors.background })
hi(0, '@comment.hint', { bg = '#89b4fb', fg = colors.background })
hi(0, '@comment.note', { bg = '#89b4fb', fg = colors.background })
hi(0, '@comment.todo', { bg = '#f2cdce', fg = colors.background })
hi(0, '@comment.warning', { bg = '#f9e2b0', fg = colors.background })
hi(0, '@comment.warning.gitcommit', { fg = '#f9e2b0' })
hi(0, '@conditional', { link = 'Conditional' })
hi(0, '@constant.builtin', { fg = '#fab388' })
hi(0, '@constant.java', { fg = '#94e2d6' })
hi(0, '@constant.macro', { link = 'Macro' })
hi(0, '@constructor', { fg = '#74c7ed' })
hi(0, '@constructor.lua', { fg = '#f2cdce' })
hi(0, '@constructor.tsx', { fg = '#b4beff' })
hi(0, '@constructor.typescript', { fg = '#b4beff' })
hi(0, '@define', { link = 'Define' })
hi(0, '@diff.delta', { link = 'DiffChanged' })
hi(0, '@diff.minus', { link = 'DiffRemoved' })
hi(0, '@diff.plus', { link = 'DiffAdded' })
hi(0, '@error', { link = 'Error' })
hi(0, '@exception', { link = 'Exception' })
hi(0, '@field', { fg = '#b4beff' })
hi(0, '@float', { link = 'Float' })
hi(0, '@function.builtin', { link = 'Function' })
hi(0, '@function.builtin.bash', { fg = '#f38ba9', italic = true })
hi(0, '@function.call', { link = 'Function' })
hi(0, '@function.macro', { fg = colors.rose })
hi(0, '@function.method', { link = 'Function' })
hi(0, '@function.method.call', { link = 'Function' })
hi(0, '@function.method.call.php', { link = 'Function' })
hi(0, '@function.method.php', { link = 'Function' })
hi(0, '@ibl.indent.char.1', { fg = '#313245', nocombine = true })
hi(0, '@ibl.scope.char.1', { fg = colors.yellow, nocombine = true })
hi(0, '@ibl.scope.char.2', { fg = colors.purple, nocombine = true })
hi(0, '@ibl.scope.char.3', { fg = colors.blue, nocombine = true })
hi(0, '@ibl.scope.char.4', { fg = colors.orange, nocombine = true })
hi(0, '@ibl.scope.char.5', { fg = colors.green, nocombine = true })
hi(0, '@ibl.scope.char.6', { fg = colors.teal, nocombine = true })
hi(0, '@ibl.scope.underline.1', { sp = colors.yellow, underline = true })
hi(0, '@ibl.scope.underline.2', { sp = colors.purple, underline = true })
hi(0, '@ibl.scope.underline.3', { sp = colors.blue, underline = true })
hi(0, '@ibl.scope.underline.4', { sp = colors.orange, underline = true })
hi(0, '@ibl.scope.underline.5', { sp = colors.green, underline = true })
hi(0, '@ibl.scope.underline.6', { sp = colors.teal, underline = true })
hi(0, '@ibl.whitespace.char.1', { fg = '#45475b', nocombine = true })
hi(0, '@include', { link = 'Include' })
hi(0, '@keyword.conditional', { link = 'Conditional' })
hi(0, '@keyword.conditional.ternary', { link = 'Operator' })
hi(0, '@keyword.coroutine', { link = 'Keyword' })
hi(0, '@keyword.debug', { link = 'Exception' })
hi(0, '@keyword.directive', { link = 'PreProc' })
hi(0, '@keyword.directive.define', { link = 'Define' })
hi(0, '@keyword.exception', { link = 'Conditional' })
hi(0, '@keyword.export', { fg = '#89dcec' })
hi(0, '@keyword.function', { fg = '#cba6f8' })
hi(0, '@keyword.import', { link = 'Include' })
hi(0, '@keyword.modifier', { link = 'Keyword' })
hi(0, '@keyword.operator', { link = 'Keyword' })
hi(0, '@keyword.repeat', { link = 'Conditional' })
hi(0, '@keyword.return', { link = 'Conditional' })
hi(0, '@keyword.storage', { link = 'Keyword' })
hi(0, '@keyword.type', { link = 'Keyword' })
hi(0, '@label.json', { fg = '#89b4fb' })
hi(0, '@lsp.type.boolean', { link = '@boolean' })
hi(0, '@lsp.type.builtinType', { link = '@type.builtin' })
hi(0, '@lsp.type.comment', { link = '@comment' })
hi(0, '@lsp.type.enum', { link = '@type' })
hi(0, '@lsp.type.enumMember', { link = '@constant' })
hi(0, '@lsp.type.escapeSequence', { link = '@string.escape' })
hi(0, '@lsp.type.formatSpecifier', { link = '@punctuation.special' })
hi(0, '@lsp.type.interface', { fg = '#f2cdce' })
hi(0, '@lsp.type.keyword', { link = '@keyword' })
hi(0, '@lsp.type.namespace', { link = '@module' })
hi(0, '@lsp.type.number', { link = '@number' })
hi(0, '@lsp.type.operator', { link = '@operator' })
hi(0, '@lsp.type.parameter', { link = '@parameter' })
hi(0, '@lsp.type.property', { link = '@property' })
hi(0, '@lsp.type.selfKeyword', { link = '@variable.builtin' })
hi(0, '@lsp.type.typeAlias', { link = '@type.definition' })
hi(0, '@lsp.type.unresolvedReference', { link = '@error' })
hi(0, '@lsp.type.variable', {})
-- hi(0, '@lsp.typemod.class.defaultLibrary', { link = '@type.builtin' })
-- hi(0, '@lsp.typemod.enum.defaultLibrary', { link = '@type.builtin' })
-- hi(0, '@lsp.typemod.enumMember.defaultLibrary', { link = '@constant.builtin' })
-- hi(0, '@lsp.typemod.function.defaultLibrary', { link = '@function.builtin' })
hi(0, '@lsp.typemod.keyword.async', { link = '@keyword.coroutine' })
-- hi(0, '@lsp.typemod.macro.defaultLibrary', { link = '@function.builtin' })
-- hi(0, '@lsp.typemod.method.defaultLibrary', { link = '@function.builtin' })
hi(0, '@lsp.typemod.operator.injected', { link = '@operator' })
hi(0, '@lsp.typemod.string.injected', { link = '@string' })
hi(0, '@lsp.typemod.type.defaultLibrary', { link = '@type.builtin' })
hi(0, '@lsp.typemod.variable.defaultLibrary', { link = '@variable' })
hi(0, '@lsp.typemod.variable.injected', { link = '@variable' })
hi(0, '@markup', { fg = '#cdd6f5' })
hi(0, '@markup.environment', { fg = '#f5c2e8' })
hi(0, '@markup.environment.name', { fg = '#89b4fb' })
hi(0, '@markup.heading', { bold = true, fg = '#89b4fb' })
hi(0, '@markup.heading.1.delimiter.vimdoc',
	{ bg = colors.background, fg = '#1e1e2f', nocombine = true, sp = '#cdd6f5', underdouble = true })
hi(0, '@markup.heading.1.markdown', { link = 'rainbow1' })
hi(0, '@markup.heading.2.delimiter.vimdoc',
	{ bg = colors.background, fg = '#1e1e2f', nocombine = true, sp = '#cdd6f5', underline = true })
hi(0, '@markup.heading.2.markdown', { link = 'rainbow2' })
hi(0, '@markup.heading.3.markdown', { link = 'rainbow3' })
hi(0, '@markup.heading.4.markdown', { link = 'rainbow4' })
hi(0, '@markup.heading.5.markdown', { link = 'rainbow5' })
hi(0, '@markup.heading.6.markdown', { link = 'rainbow6' })
hi(0, '@markup.italic', { fg = '#eba0ad', italic = true })
hi(0, '@markup.link', { link = 'Tag' })
hi(0, '@markup.link.label', { link = 'Label' })
hi(0, '@markup.link.url', { fg = '#f5e0dd', italic = true, underline = true })
hi(0, '@markup.list', { link = 'Special' })
hi(0, '@markup.list.checked', { fg = '#a6e3a2' })
hi(0, '@markup.list.unchecked', { fg = '#7f849d' })
hi(0, '@markup.math', { fg = '#89b4fb' })
hi(0, '@markup.quote', { bold = true, fg = '#eba0ad' })
hi(0, '@markup.raw', { fg = '#94e2d6' })
hi(0, '@markup.strikethrough', { fg = '#cdd6f5', strikethrough = true })
hi(0, '@markup.strong', { bold = true, fg = '#eba0ad' })
hi(0, '@markup.underline', { link = 'Underlined' })
hi(0, '@method', { link = 'Function' })
hi(0, '@method.call', { link = 'Function' })
hi(0, '@method.call.php', { link = 'Function' })
hi(0, '@method.php', { link = 'Function' })
hi(0, '@module', { fg = '#b4beff', italic = true })
hi(0, '@namespace', { fg = '#b4beff', italic = true })
hi(0, '@number.css', { fg = '#fab388' })
hi(0, '@number.float', { link = 'Float' })
hi(0, '@parameter', { fg = '#eba0ad' })
hi(0, '@preproc', { link = 'PreProc' })
hi(0, '@property', { fg = colors.teal })
hi(0, '@property.class.css', { fg = '#f9e2b0' })
hi(0, '@property.cpp', { fg = '#cdd6f5' })
hi(0, '@property.css', { fg = '#b4beff' })
hi(0, '@property.id.css', { fg = '#89b4fb' })
hi(0, '@property.toml', { fg = '#89b4fb' })
hi(0, '@property.typescript', { fg = '#b4beff' })
hi(0, '@punctuation.bracket', { link = 'Delimiter' })
hi(0, '@punctuation.delimiter', { link = 'Delimiter' })
hi(0, '@punctuation.special', { link = 'Special' })
hi(0, '@repeat', { link = 'Repeat' })
hi(0, '@storageclass', { link = 'Keyword' })
hi(0, '@string.documentation', { fg = '#94e2d6' })
hi(0, '@string.escape', { fg = '#f5c2e8' })
hi(0, '@string.plain.css', { fg = '#fab388' })
hi(0, '@string.regex', { fg = '#fab388' })
hi(0, '@string.regexp', { fg = '#fab388' })
hi(0, '@string.pecial', { link = 'Special' })
hi(0, '@string.special.path', { link = 'Special' })
hi(0, '@string.special.path.gitignore', { fg = '#cdd6f5' })
hi(0, '@string.special.symbol', { fg = '#f2cdce' })
hi(0, '@string.special.symbol.ruby', { fg = '#f2cdce' })
hi(0, '@string.special.url', { fg = '#f5e0dd', italic = true, underline = true })
hi(0, '@symbol', { fg = '#f2cdce' })
hi(0, '@symbol.ruby', { fg = '#f2cdce' })
hi(0, '@tag', { fg = '#cba6f8' })
hi(0, '@tag.attribute', { fg = '#94e2d6', italic = true })
hi(0, '@tag.attribute.tsx', { fg = '#94e2d6', italic = true })
hi(0, '@tag.delimiter', { fg = '#89dcec' })
hi(0, '@text', { fg = '#cdd6f5' })
hi(0, '@text.danger', { bg = '#f38ba9', fg = colors.background })
hi(0, '@text.diff.add', { link = 'DiffAdded' })
hi(0, '@text.diff.delete', { link = 'DiffRemoved' })
hi(0, '@text.emphasis', { fg = '#eba0ad', italic = true })
hi(0, '@text.environment', { fg = '#f5c2e8' })
hi(0, '@text.environment.name', { fg = '#89b4fb' })
hi(0, '@text.literal', { fg = '#94e2d6' })
hi(0, '@text.math', { fg = '#89b4fb' })
hi(0, '@text.note', { bg = '#89b4fb', fg = colors.background })
hi(0, '@text.reference', { link = 'Tag' })
hi(0, '@text.strike', { fg = '#cdd6f5', strikethrough = true })
hi(0, '@text.strong', { bold = true, fg = '#eba0ad' })
hi(0, '@text.title', { bold = true, fg = '#89b4fb' })
hi(0, '@text.title.1.markdown', { link = 'rainbow1' })
hi(0, '@text.title.2.markdown', { link = 'rainbow2' })
hi(0, '@text.title.3.markdown', { link = 'rainbow3' })
hi(0, '@text.title.4.markdown', { link = 'rainbow4' })
hi(0, '@text.title.5.markdown', { link = 'rainbow5' })
hi(0, '@text.title.6.markdown', { link = 'rainbow6' })
hi(0, '@text.todo', { bg = '#f2cdce', fg = colors.background })
hi(0, '@text.todo.checked', { fg = '#a6e3a2' })
hi(0, '@text.todo.unchecked', { fg = '#7f849d' })
hi(0, '@text.underline', { link = 'Underlined' })
hi(0, '@text.warning', { bg = '#f9e2b0', fg = colors.background })
hi(0, '@type.builtin', { fg = '#f9e2b0' })
hi(0, '@type.builtin.c', { fg = '#f9e2b0' })
hi(0, '@type.builtin.cpp', { fg = '#f9e2b0' })
hi(0, '@type.css', { fg = '#b4beff' })
hi(0, '@type.definition', { link = 'Type' })
hi(0, '@type.qualifier', { link = 'Keyword' })
hi(0, '@type.tag.css', { fg = '#cba6f8' })
hi(0, '@variable', { fg = '#cdd6f5' })
hi(0, '@variable.builtin', { link = 'Keyword' })
hi(0, '@variable.member', { fg = colors.teal })
hi(0, '@variable.parameter', { fg = '#eba0ad' })
hi(0, 'AlphaButtons', { fg = '#b4beff' })
hi(0, 'AlphaFooter', { fg = '#f9e2b0', italic = true })
hi(0, 'AlphaHeader', { fg = '#89b4fb' })
hi(0, 'AlphaHeaderLabel', { fg = '#fab388' })
hi(0, 'AlphaShortcut', { fg = '#a6e3a2' })
hi(0, 'BlinkCmpKind', { fg = '#89b4fb' })
hi(0, 'BlinkCmpKindClass', { fg = '#f9e2b0' })
hi(0, 'BlinkCmpKindColor', { fg = '#f38ba9' })
hi(0, 'BlinkCmpKindConstant', { fg = '#fab388' })
hi(0, 'BlinkCmpKindConstructor', { fg = '#89b4fb' })
hi(0, 'BlinkCmpKindCopilot', { fg = '#94e2d6' })
hi(0, 'BlinkCmpKindEnum', { fg = '#f9e2b0' })
hi(0, 'BlinkCmpKindEnumMember', { fg = '#94e2d6' })
hi(0, 'BlinkCmpKindEvent', { fg = '#89b4fb' })
hi(0, 'BlinkCmpKindField', { fg = '#a6e3a2' })
hi(0, 'BlinkCmpKindFile', { fg = '#89b4fb' })
hi(0, 'BlinkCmpKindFolder', { fg = '#89b4fb' })
hi(0, 'BlinkCmpKindFunction', { fg = '#89b4fb' })
hi(0, 'BlinkCmpKindInterface', { fg = '#f9e2b0' })
hi(0, 'BlinkCmpKindKeyword', { fg = '#cba6f8' })
hi(0, 'BlinkCmpKindMethod', { fg = '#89b4fb' })
hi(0, 'BlinkCmpKindModule', { fg = '#89b4fb' })
hi(0, 'BlinkCmpKindOperator', { fg = colors.blue })
hi(0, 'BlinkCmpKindProperty', { fg = '#89b4fb' })
hi(0, 'BlinkCmpKindReference', { fg = '#f38ba9' })
hi(0, 'BlinkCmpKindSnippet', { fg = '#f2cdce' })
hi(0, 'BlinkCmpKindStruct', { fg = '#89b4fb' })
hi(0, 'BlinkCmpKindText', { fg = '#a6e3a2' })
hi(0, 'BlinkCmpKindTypeParameter', { fg = '#eba0ad' })
hi(0, 'BlinkCmpKindUnit', { fg = '#a6e3a2' })
hi(0, 'BlinkCmpKindValue', { fg = '#fab388' })
hi(0, 'BlinkCmpKindVariable', { fg = '#f2cdce' })
hi(0, 'BlinkCmpLabel', { fg = '#9399b3' })
hi(0, 'BlinkCmpLabelDeprecated', { fg = '#6c7087', strikethrough = true })
hi(0, 'BlinkCmpLabelDescription', { fg = '#6c7087' })
hi(0, 'BlinkCmpLabelDetail', { fg = '#6c7087' })
hi(0, 'BlinkCmpLabelMatch', { bold = true, fg = '#cdd6f5' })
hi(0, 'BlinkCmpMenuSelection', { bg = '#45475b', bold = true })
hi(0, 'BlinkCmpScrollBarGutter', { bg = '#45475b' })
hi(0, 'BlinkCmpScrollBarThumb', { bg = '#6c7087' })
hi(0, 'Bold', { bold = true })
hi(0, 'Boolean', { fg = '#fab388' })
hi(0, 'Character', { fg = colors.red })
hi(0, 'CmpItemAbbr', { fg = '#9399b3' })
hi(0, 'CmpItemAbbrDefault', { fg = '#9399b3' })
hi(0, 'CmpItemAbbrDeprecated', { fg = '#6c7087', strikethrough = true })
hi(0, 'CmpItemAbbrDeprecatedDefault', { fg = '#9399b3' })
hi(0, 'CmpItemAbbrMatch', { bold = true, fg = '#cdd6f5' })
hi(0, 'CmpItemAbbrMatchDefault', { fg = '#9399b3' })
hi(0, 'CmpItemAbbrMatchFuzzy', { bold = true, fg = '#cdd6f5' })
hi(0, 'CmpItemAbbrMatchFuzzyDefault', { fg = '#9399b3' })
hi(0, 'CmpItemKind', { fg = '#89b4fb' })
hi(0, 'CmpItemKindClass', { fg = '#f9e2b0' })
hi(0, 'CmpItemKindClassDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindColor', { fg = '#f38ba9' })
hi(0, 'CmpItemKindColorDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindConstant', { fg = '#fab388' })
hi(0, 'CmpItemKindConstantDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindConstructor', { fg = '#89b4fb' })
hi(0, 'CmpItemKindConstructorDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindCopilot', { fg = '#94e2d6' })
hi(0, 'CmpItemKindDefault', { fg = '#f5c2e8' })
hi(0, 'CmpItemKindEnum', { fg = '#a6e3a2' })
hi(0, 'CmpItemKindEnumDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindEnumMember', { fg = '#f38ba9' })
hi(0, 'CmpItemKindEnumMemberDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindEvent', { fg = '#89b4fb' })
hi(0, 'CmpItemKindEventDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindField', { fg = '#a6e3a2' })
hi(0, 'CmpItemKindFieldDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindFile', { fg = '#89b4fb' })
hi(0, 'CmpItemKindFileDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindFolder', { fg = '#89b4fb' })
hi(0, 'CmpItemKindFolderDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindFunction', { fg = '#89b4fb' })
hi(0, 'CmpItemKindFunctionDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindInterface', { fg = '#f9e2b0' })
hi(0, 'CmpItemKindInterfaceDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindKeyword', { fg = '#f38ba9' })
hi(0, 'CmpItemKindKeywordDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindMethod', { fg = '#89b4fb' })
hi(0, 'CmpItemKindMethodDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindModule', { fg = '#89b4fb' })
hi(0, 'CmpItemKindModuleDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindOperator', { fg = '#89b4fb' })
hi(0, 'CmpItemKindOperatorDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindProperty', { fg = '#a6e3a2' })
hi(0, 'CmpItemKindPropertyDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindReference', { fg = '#f38ba9' })
hi(0, 'CmpItemKindReferenceDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindSnippet', { fg = '#cba6f8' })
hi(0, 'CmpItemKindSnippetDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindStruct', { fg = '#89b4fb' })
hi(0, 'CmpItemKindStructDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindText', { fg = '#94e2d6' })
hi(0, 'CmpItemKindTextDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindTypeParameter', { fg = '#89b4fb' })
hi(0, 'CmpItemKindTypeParameterDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindUnit', { fg = '#a6e3a2' })
hi(0, 'CmpItemKindUnitDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindValue', { fg = '#fab388' })
hi(0, 'CmpItemKindValueDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindVariable', { fg = '#f2cdce' })
hi(0, 'CmpItemKindVariableDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemMenu', { fg = '#cdd6f5' })
hi(0, 'CmpItemMenuDefault', { fg = '#9399b3' })
hi(0, 'ColorColumn', { bg = '#313245' })
hi(0, 'Comment', { fg = '#9399b3', italic = true })
hi(0, 'Conceal', { fg = '#7f849d' })
hi(0, 'Conditional', { fg = '#cba6f8', italic = true })
hi(0, 'Constant', { fg = '#fab388' })
hi(0, 'CurSearch', { bg = '#f38ba9', fg = '#181826' })
hi(0, 'Cursor', { bg = '#f5e0dd', fg = colors.background })
hi(0, 'CursorColumn', { bg = '#181826' })
hi(0, 'CursorIM', { bg = '#f5e0dd', fg = colors.background })
hi(0, 'CursorLine', { bg = '#2a2b3d' })
hi(0, 'CursorLineNr', { fg = '#b4beff' })
hi(0, 'DapBreakpoint', { fg = '#f38ba9' })
hi(0, 'DapBreakpointCondition', { fg = '#f9e2b0' })
hi(0, 'DapBreakpointRejected', { fg = '#cba6f8' })
hi(0, 'DapLogPoint', { fg = '#89dcec' })
hi(0, 'DapStopped', { fg = '#eba0ad' })
hi(0, 'DapUIBreakpointsCurrentLine', { bold = true, fg = '#a6e3a2' })
hi(0, 'DapUIBreakpointsDisabledLine', { fg = '#585b71' })
hi(0, 'DapUIBreakpointsInfo', { fg = '#a6e3a2' })
hi(0, 'DapUIBreakpointsPath', { fg = '#89dcec' })
hi(0, 'DapUIDecoration', { fg = '#89dcec' })
hi(0, 'DapUIFloatBorder', { link = 'FloatBorder' })
hi(0, 'DapUILineNumber', { fg = '#89dcec' })
hi(0, 'DapUIModifiedValue', { fg = '#fab388' })
hi(0, 'DapUIPlayPause', { fg = '#a6e3a2' })
hi(0, 'DapUIPlayPauseNC', { link = 'DapUIPlayPause' })
hi(0, 'DapUIRestart', { fg = '#a6e3a2' })
hi(0, 'DapUIRestartNC', { link = 'DapUIRestart' })
hi(0, 'DapUIScope', { fg = '#89dcec' })
hi(0, 'DapUISource', { fg = '#b4beff' })
hi(0, 'DapUIStepBack', { fg = '#89b4fb' })
hi(0, 'DapUIStepBackNC', { link = 'DapUIStepBack' })
hi(0, 'DapUIStepInto', { fg = '#89b4fb' })
hi(0, 'DapUIStepIntoNC', { link = 'DapUIStepInto' })
hi(0, 'DapUIStepOut', { fg = '#89b4fb' })
hi(0, 'DapUIStepOutNC', { link = 'DapUIStepOut' })
hi(0, 'DapUIStepOver', { fg = '#89b4fb' })
hi(0, 'DapUIStepOverNC', { link = 'DapUIStepOver' })
hi(0, 'DapUIStop', { fg = '#f38ba9' })
hi(0, 'DapUIStopNC', { link = 'DapUIStop' })
hi(0, 'DapUIStoppedThread', { fg = '#89dcec' })
hi(0, 'DapUIThread', { fg = '#a6e3a2' })
hi(0, 'DapUIType', { fg = '#cba6f8' })
hi(0, 'DapUIUnavailable', { fg = '#45475b' })
hi(0, 'DapUIUnavailableNC', { link = 'DapUIUnavailable' })
hi(0, 'DapUIValue', { fg = '#89dcec' })
hi(0, 'DapUIVariable', { fg = '#cdd6f5' })
hi(0, 'DapUIWatchesEmpty', { fg = '#eba0ad' })
hi(0, 'DapUIWatchesError', { fg = '#eba0ad' })
hi(0, 'DapUIWatchesValue', { fg = '#a6e3a2' })
hi(0, 'DapUIWinSelect', { fg = '#fab388' })
hi(0, 'DashboardCenter', { fg = '#a6e3a2' })
hi(0, 'DashboardDesc', { fg = '#89b4fb' })
hi(0, 'DashboardFiles', { fg = '#b4beff' })
hi(0, 'DashboardFooter', { fg = '#f9e2b0', italic = true })
hi(0, 'DashboardHeader', { fg = '#89b4fb' })
hi(0, 'DashboardIcon', { bold = true, fg = '#f5c2e8' })
hi(0, 'DashboardKey', { fg = '#fab388' })
hi(0, 'DashboardMruTitle', { fg = '#89dcec' })
hi(0, 'DashboardProjectTitle', { fg = '#89dcec' })
hi(0, 'DashboardShortCut', { fg = '#f5c2e8' })
hi(0, 'Delimiter', { fg = '#9399b3' })
hi(0, 'DiagnosticError', { fg = '#f38ba9', italic = true })
hi(0, 'DiagnosticFloatingError', { fg = '#f38ba9' })
hi(0, 'DiagnosticFloatingHint', { fg = '#94e2d6' })
hi(0, 'DiagnosticFloatingInfo', { fg = '#89dcec' })
hi(0, 'DiagnosticFloatingOk', { fg = '#a6e3a2' })
hi(0, 'DiagnosticFloatingWarn', { fg = '#f9e2b0' })
hi(0, 'DiagnosticHint', { fg = '#94e2d6', italic = true })
hi(0, 'DiagnosticInfo', { fg = '#89dcec', italic = true })
hi(0, 'DiagnosticOk', { fg = '#a6e3a2', italic = true })
hi(0, 'DiagnosticSignError', { fg = '#f38ba9' })
hi(0, 'DiagnosticSignHint', { fg = '#94e2d6' })
hi(0, 'DiagnosticSignInfo', { fg = '#89dcec' })
hi(0, 'DiagnosticSignOk', { fg = '#a6e3a2' })
hi(0, 'DiagnosticSignWarn', { fg = '#f9e2b0' })
hi(0, 'DiagnosticUnderlineError', { sp = '#f38ba9', underline = true })
hi(0, 'DiagnosticUnderlineHint', { sp = '#94e2d6', underline = true })
hi(0, 'DiagnosticUnderlineInfo', { sp = '#89dcec', underline = true })
hi(0, 'DiagnosticUnderlineOk', { sp = '#a6e3a2', underline = true })
hi(0, 'DiagnosticUnderlineWarn', { sp = '#f9e2b0', underline = true })
hi(0, 'DiagnosticVirtualTextError', { bg = '#32283b', fg = '#f38ba9', italic = true })
hi(0, 'DiagnosticVirtualTextHint', { bg = '#29313f', fg = '#94e2d6', italic = true })
hi(0, 'DiagnosticVirtualTextInfo', { bg = '#283041', fg = '#89dcec', italic = true })
hi(0, 'DiagnosticVirtualTextOk', { bg = '#29313f', fg = '#a6e3a2', italic = true })
hi(0, 'DiagnosticVirtualTextWarn', { bg = '#33313b', fg = '#f9e2b0', italic = true })
hi(0, 'DiagnosticWarn', { fg = '#f9e2b0', italic = true })
hi(0, 'DiffAdd', { bg = '#364144' })
hi(0, 'DiffAdded', { fg = '#a6e3a2' })
hi(0, 'DiffChange', { bg = '#25293d' })
hi(0, 'DiffChanged', { fg = '#89b4fb' })
hi(0, 'DiffDelete', { bg = '#443245' })
hi(0, 'DiffFile', { fg = '#89b4fb' })
hi(0, 'DiffIndexLine', { fg = '#94e2d6' })
hi(0, 'DiffRemoved', { fg = '#f38ba9' })
hi(0, 'DiffText', { bg = '#3e4b6c' })
hi(0, 'Directory', { fg = '#89b4fb' })
hi(0, 'DropBarIconUISeparator', { fg = '#7f849d' })
hi(0, 'DropBarKindArray', { fg = '#cdd6f5' })
hi(0, 'DropBarKindBoolean', { fg = '#cdd6f5' })
hi(0, 'DropBarKindBreakStatement', { fg = '#cdd6f5' })
hi(0, 'DropBarKindCall', { fg = '#cdd6f5' })
hi(0, 'DropBarKindCaseStatement', { fg = '#cdd6f5' })
hi(0, 'DropBarKindClass', { fg = '#cdd6f5' })
hi(0, 'DropBarKindConstant', { fg = '#cdd6f5' })
hi(0, 'DropBarKindConstructor', { fg = '#cdd6f5' })
hi(0, 'DropBarKindContinueStatement', { fg = '#cdd6f5' })
hi(0, 'DropBarKindDeclaration', { fg = '#cdd6f5' })
hi(0, 'DropBarKindDelete', { fg = '#cdd6f5' })
hi(0, 'DropBarKindDoStatement', { fg = '#cdd6f5' })
hi(0, 'DropBarKindElseStatement', { fg = '#cdd6f5' })
hi(0, 'DropBarKindEnum', { fg = '#cdd6f5' })
hi(0, 'DropBarKindEnumMember', { fg = '#cdd6f5' })
hi(0, 'DropBarKindEvent', { fg = '#cdd6f5' })
hi(0, 'DropBarKindField', { fg = '#cdd6f5' })
hi(0, 'DropBarKindFile', { fg = '#cdd6f5' })
hi(0, 'DropBarKindFolder', { fg = '#cdd6f5' })
hi(0, 'DropBarKindForStatement', { fg = '#cdd6f5' })
hi(0, 'DropBarKindFunction', { fg = '#cdd6f5' })
hi(0, 'DropBarKindIdentifier', { fg = '#cdd6f5' })
hi(0, 'DropBarKindIfStatement', { fg = '#cdd6f5' })
hi(0, 'DropBarKindInterface', { fg = '#cdd6f5' })
hi(0, 'DropBarKindKeyword', { fg = '#cdd6f5' })
hi(0, 'DropBarKindList', { fg = '#cdd6f5' })
hi(0, 'DropBarKindMacro', { fg = '#cdd6f5' })
hi(0, 'DropBarKindMarkdownH1', { fg = '#cdd6f5' })
hi(0, 'DropBarKindMarkdownH2', { fg = '#cdd6f5' })
hi(0, 'DropBarKindMarkdownH3', { fg = '#cdd6f5' })
hi(0, 'DropBarKindMarkdownH4', { fg = '#cdd6f5' })
hi(0, 'DropBarKindMarkdownH5', { fg = '#cdd6f5' })
hi(0, 'DropBarKindMarkdownH6', { fg = '#cdd6f5' })
hi(0, 'DropBarKindMethod', { fg = '#cdd6f5' })
hi(0, 'DropBarKindModule', { fg = '#cdd6f5' })
hi(0, 'DropBarKindNamespace', { fg = '#cdd6f5' })
hi(0, 'DropBarKindNull', { fg = '#cdd6f5' })
hi(0, 'DropBarKindNumber', { fg = '#cdd6f5' })
hi(0, 'DropBarKindObject', { fg = '#cdd6f5' })
hi(0, 'DropBarKindOperator', { fg = '#cdd6f5' })
hi(0, 'DropBarKindPackage', { fg = '#cdd6f5' })
hi(0, 'DropBarKindProperty', { fg = '#cdd6f5' })
hi(0, 'DropBarKindReference', { fg = '#cdd6f5' })
hi(0, 'DropBarKindRepeat', { fg = '#cdd6f5' })
hi(0, 'DropBarKindScope', { fg = '#cdd6f5' })
hi(0, 'DropBarKindSpecifier', { fg = '#cdd6f5' })
hi(0, 'DropBarKindStatement', { fg = '#cdd6f5' })
hi(0, 'DropBarKindString', { fg = '#cdd6f5' })
hi(0, 'DropBarKindStruct', { fg = '#cdd6f5' })
hi(0, 'DropBarKindSwitchStatement', { fg = '#cdd6f5' })
hi(0, 'DropBarKindType', { fg = '#cdd6f5' })
hi(0, 'DropBarKindTypeParameter', { fg = '#cdd6f5' })
hi(0, 'DropBarKindUnit', { fg = '#cdd6f5' })
hi(0, 'DropBarKindValue', { fg = '#cdd6f5' })
hi(0, 'DropBarKindVariable', { fg = '#cdd6f5' })
hi(0, 'DropBarKindWhileStatement', { fg = '#cdd6f5' })
hi(0, 'DropBarMenuHoverEntry', { link = 'Visual' })
hi(0, 'DropBarMenuHoverIcon', { reverse = true })
hi(0, 'DropBarMenuHoverSymbol', { bold = true })
hi(0, 'EndOfBuffer', { fg = colors.background })
hi(0, 'Error', { fg = '#f38ba9' })
hi(0, 'ErrorMsg', { bold = true, fg = '#f38ba9', italic = true })
hi(0, 'Exception', { fg = '#cba6f8' })
hi(0, 'FlashBackdrop', { fg = '#6c7087' })
hi(0, 'FlashCurrent', { bg = colors.background, fg = '#fab388' })
hi(0, 'FlashLabel', { bg = colors.background, bold = true, fg = '#a6e3a2' })
hi(0, 'FlashMatch', { bg = colors.background, fg = '#b4beff' })
hi(0, 'FlashPrompt', { link = 'NormalFloat' })
hi(0, 'FloatBorder', { fg = '#89b4fb' })
hi(0, 'FloatTitle', { fg = '#a6adc9' })
hi(0, 'FoldColumn', { fg = '#6c7087' })
hi(0, 'Folded', { bg = '#45475b', fg = '#89b4fb' })
hi(0, 'Function', { fg = '#89b4fb' })
hi(0, 'FzfLuaBorder', { link = 'FloatBorder' })
hi(0, 'FzfLuaBufFlagAlt', { fg = '#89b4fb' })
hi(0, 'FzfLuaBufFlagCur', { fg = '#fab388' })
hi(0, 'FzfLuaBufName', { fg = '#cba6f8' })
hi(0, 'FzfLuaBufNr', { fg = '#f9e2b0' })
hi(0, 'FzfLuaDirPart', { link = 'NonText' })
hi(0, 'FzfLuaFzfMatch', { fg = '#89b4fb' })
hi(0, 'FzfLuaFzfPrompt', { fg = '#89b4fb' })
hi(0, 'FzfLuaHeaderBind', { fg = '#f9e2b0' })
hi(0, 'FzfLuaHeaderText', { fg = '#fab388' })
hi(0, 'FzfLuaLiveSym', { fg = '#fab388' })
hi(0, 'FzfLuaPathColNr', { fg = '#89b4fb' })
hi(0, 'FzfLuaPathLineNr', { fg = '#a6e3a2' })
hi(0, 'FzfLuaTabMarker', { fg = '#f9e2b0' })
hi(0, 'FzfLuaTabTitle', { fg = '#89dcec' })
hi(0, 'FzfLuaTitle', { link = 'FloatBorder' })
hi(0, 'GitSignsAdd', { fg = '#a6e3a2' })
hi(0, 'GitSignsAddInline', { bg = '#4f6558' })
hi(0, 'GitSignsAddPreview', { link = 'DiffAdd' })
hi(0, 'GitSignsChange', { fg = '#f9e2b0' })
hi(0, 'GitSignsChangeInline', { bg = '#2d334c' })
hi(0, 'GitSignsCurrentLineBlame', { fg = '#45475b' })
hi(0, 'GitSignsDelete', { fg = '#f38ba9' })
hi(0, 'GitSignsDeleteInline', { bg = '#6b455b' })
hi(0, 'GitSignsDeletePreview', { link = 'DiffDelete' })
hi(0, 'GlyphPalette1', { fg = '#f38ba9' })
hi(0, 'GlyphPalette2', { fg = '#94e2d6' })
hi(0, 'GlyphPalette3', { fg = '#f9e2b0' })
hi(0, 'GlyphPalette4', { fg = '#89b4fb' })
hi(0, 'GlyphPalette6', { fg = '#94e2d6' })
hi(0, 'GlyphPalette7', { fg = '#cdd6f5' })
hi(0, 'GlyphPalette9', { fg = '#f38ba9' })
hi(0, 'IblIndent', { fg = '#313245' })
hi(0, 'IblScope', { fg = '#cdd6f5' })
hi(0, 'IblWhitespace', { fg = '#45475b' })
hi(0, 'Identifier', { fg = '#f2cdce' })
hi(0, 'IlluminatedWordRead', { bg = '#393b4e' })
hi(0, 'IlluminatedWordText', { bg = '#393b4e' })
hi(0, 'IlluminatedWordWrite', { bg = '#393b4e' })
hi(0, 'IncSearch', { bg = '#7ec9d9', fg = '#181826' })
hi(0, 'Include', { link = 'Special' })
hi(0, 'Italic', { italic = true })
hi(0, 'Keyword', { fg = '#cba6f8' })
hi(0, 'Label', { fg = '#74c7ed' })
hi(0, 'LineNr', { fg = '#45475b' })
hi(0, 'LspCodeLens', { fg = '#6c7087' })
hi(0, 'LspDiagnosticsDefaultError', { fg = '#f38ba9' })
hi(0, 'LspDiagnosticsDefaultHint', { fg = '#94e2d6' })
hi(0, 'LspDiagnosticsDefaultInformation', { fg = '#89dcec' })
hi(0, 'LspDiagnosticsDefaultWarning', { fg = '#f9e2b0' })
hi(0, 'LspDiagnosticsError', { fg = '#f38ba9' })
hi(0, 'LspDiagnosticsHint', { fg = '#94e2d6' })
hi(0, 'LspDiagnosticsInformation', { fg = '#89dcec' })
hi(0, 'LspDiagnosticsUnderlineError', { sp = '#f38ba9', underline = true })
hi(0, 'LspDiagnosticsUnderlineHint', { sp = '#94e2d6', underline = true })
hi(0, 'LspDiagnosticsUnderlineInformation', { sp = '#89dcec', underline = true })
hi(0, 'LspDiagnosticsUnderlineWarning', { sp = '#f9e2b0', underline = true })
hi(0, 'LspDiagnosticsVirtualTextError', { fg = '#f38ba9', italic = true })
hi(0, 'LspDiagnosticsVirtualTextHint', { fg = '#94e2d6', italic = true })
hi(0, 'LspDiagnosticsVirtualTextInformation', { fg = '#89dcec', italic = true })
hi(0, 'LspDiagnosticsVirtualTextWarning', { fg = '#f9e2b0', italic = true })
hi(0, 'LspDiagnosticsWarning', { fg = '#f9e2b0' })
hi(0, 'LspInfoBorder', { link = 'FloatBorder' })
hi(0, 'LspInlayHint', { bg = '#2a2b3d', fg = '#6c7087' })
hi(0, 'LspReferenceRead', { bg = '#45475b' })
hi(0, 'LspReferenceText', { bg = '#45475b' })
hi(0, 'LspReferenceWrite', { bg = '#45475b' })
hi(0, 'LspSignatureActiveParameter', { bg = '#313245', bold = true })
hi(0, 'Macro', { fg = colors.rose })
hi(0, 'MatchParen', { bg = '#45475b', bold = true, fg = '#fab388' })
hi(0, 'MiniAnimateCursor', { nocombine = true, reverse = true })
hi(0, 'MiniAnimateNormalFloat', { link = 'NormalFloat' })
hi(0, 'MiniClueBorder', { link = 'FloatBorder' })
hi(0, 'MiniClueDescGroup', { link = 'DiagnosticFloatingWarn' })
hi(0, 'MiniClueDescSingle', { link = 'NormalFloat' })
hi(0, 'MiniClueNextKey', { link = 'DiagnosticFloatingHint' })
hi(0, 'MiniClueNextKeyWithPostkeys', { link = 'DiagnosticFloatingError' })
hi(0, 'MiniClueSeparator', { link = 'DiagnosticFloatingInfo' })
hi(0, 'MiniClueTitle', { link = 'FloatTitle' })
hi(0, 'MiniCompletionActiveParameter', { underline = true })
hi(0, 'MiniCursorword', { underline = true })
hi(0, 'MiniCursorwordCurrent', { underline = true })
hi(0, 'MiniDepsChangeAdded', { link = 'DiffAdded' })
hi(0, 'MiniDepsChangeRemoved', { link = 'DiffRemoved' })
hi(0, 'MiniDepsHint', { link = 'DiagnosticHint' })
hi(0, 'MiniDepsInfo', { link = 'DiagnosticInfo' })
hi(0, 'MiniDepsMsgBreaking', { link = 'DiagnosticWarn' })
hi(0, 'MiniDepsPlaceholder', { link = 'Comment' })
hi(0, 'MiniDepsTitle', { link = 'Title' })
hi(0, 'MiniDepsTitleError', { bg = '#f38ba9', fg = colors.background })
hi(0, 'MiniDepsTitleSame', { link = 'DiffText' })
hi(0, 'MiniDepsTitleUpdate', { bg = '#a6e3a2', fg = colors.background })
hi(0, 'MiniDiffOverAdd', { link = 'DiffAdd' })
hi(0, 'MiniDiffOverChange', { link = 'DiffText' })
hi(0, 'MiniDiffOverContext', { link = 'DiffChange' })
hi(0, 'MiniDiffOverDelete', { link = 'DiffDelete' })
hi(0, 'MiniDiffSignAdd', { fg = '#a6e3a2' })
hi(0, 'MiniDiffSignChange', { fg = '#f9e2b0' })
hi(0, 'MiniDiffSignDelete', { fg = '#f38ba9' })
hi(0, 'MiniFilesBorder', { link = 'FloatBorder' })
hi(0, 'MiniFilesBorderModified', { link = 'DiagnosticFloatingWarn' })
hi(0, 'MiniFilesCursorLine', { link = 'CursorLine' })
hi(0, 'MiniFilesDirectory', { link = 'Directory' })
hi(0, 'MiniFilesFile', { fg = '#cdd6f5' })
hi(0, 'MiniFilesNormal', { link = 'NormalFloat' })
hi(0, 'MiniFilesTitle', { link = 'FloatTitle' })
hi(0, 'MiniFilesTitleFocused', { bold = true, fg = '#a6adc9' })
hi(0, 'MiniHipatternsFixme', { bg = '#f38ba9', bold = true, fg = colors.background })
hi(0, 'MiniHipatternsHack', { bg = '#f9e2b0', bold = true, fg = colors.background })
hi(0, 'MiniHipatternsNote', { bg = '#89dcec', bold = true, fg = colors.background })
hi(0, 'MiniHipatternsTodo', { bg = '#94e2d6', bold = true, fg = colors.background })
hi(0, 'MiniIconsAzure', { fg = '#74c7ed' })
hi(0, 'MiniIconsBlue', { fg = '#89b4fb' })
hi(0, 'MiniIconsCyan', { fg = '#94e2d6' })
hi(0, 'MiniIconsGreen', { fg = '#a6e3a2' })
hi(0, 'MiniIconsGrey', { fg = '#cdd6f5' })
hi(0, 'MiniIconsOrange', { fg = '#fab388' })
hi(0, 'MiniIconsPurple', { fg = '#cba6f8' })
hi(0, 'MiniIconsRed', { fg = '#f38ba9' })
hi(0, 'MiniIconsYellow', { fg = '#f9e2b0' })
hi(0, 'MiniIndentscopeSymbol', { fg = '#9399b3' })
hi(0, 'MiniJump', { bg = '#f5c2e8', fg = '#9399b3' })
hi(0, 'MiniJump2dDim', { fg = '#6c7087' })
hi(0, 'MiniJump2dSpot', { bg = colors.background, bold = true, fg = '#fab388', underline = true })
hi(0, 'MiniJump2dSpotAhead', { bg = '#191927', fg = '#94e2d6' })
hi(0, 'MiniJump2dSpotUnique', { bg = colors.background, bold = true, fg = '#89dcec' })
hi(0, 'MiniMapNormal', { link = 'NormalFloat' })
hi(0, 'MiniMapSymbolCount', { link = 'Special' })
hi(0, 'MiniMapSymbolLine', { link = 'Title' })
hi(0, 'MiniMapSymbolView', { link = 'Delimiter' })
hi(0, 'MiniNotifyBorder', { link = 'FloatBorder' })
hi(0, 'MiniNotifyNormal', { link = 'NormalFloat' })
hi(0, 'MiniNotifyTitle', { link = 'FloatTitle' })
hi(0, 'MiniOperatorsExchangeFrom', { link = 'IncSearch' })
hi(0, 'MiniPickBorder', { link = 'FloatBorder' })
hi(0, 'MiniPickBorderBusy', { link = 'DiagnosticFloatingWarn' })
hi(0, 'MiniPickBorderText', { fg = '#cba6f8' })
hi(0, 'MiniPickHeader', { link = 'DiagnosticFloatingHint' })
hi(0, 'MiniPickIconDirectory', { link = 'Directory' })
hi(0, 'MiniPickIconFile', { link = 'MiniPickNormal' })
hi(0, 'MiniPickMatchCurrent', { link = 'CursorLine' })
hi(0, 'MiniPickMatchMarked', { link = 'Visual' })
hi(0, 'MiniPickMatchRanges', { link = 'DiagnosticFloatingHint' })
hi(0, 'MiniPickNormal', { link = 'NormalFloat' })
hi(0, 'MiniPickPreviewLine', { link = 'CursorLine' })
hi(0, 'MiniPickPreviewRegion', { link = 'IncSearch' })
hi(0, 'MiniPickPrompt', { link = 'DiagnosticFloatingInfo' })
hi(0, 'MiniStarterFooter', { fg = '#f9e2b0', italic = true })
hi(0, 'MiniStarterHeader', { fg = '#89b4fb' })
hi(0, 'MiniStarterInactive', { fg = '#585b71', italic = true })
hi(0, 'MiniStarterItem', { fg = '#cdd6f5' })
hi(0, 'MiniStarterItemBullet', { fg = '#89b4fb' })
hi(0, 'MiniStarterItemPrefix', { fg = '#f5c2e8' })
hi(0, 'MiniStarterQuery', { fg = '#a6e3a2' })
hi(0, 'MiniStarterSection', { fg = '#f2cdce' })
hi(0, 'MiniStatuslineDevinfo', { bg = '#45475b', fg = '#bac2df' })
hi(0, 'MiniStatuslineFileinfo', { bg = '#45475b', fg = '#bac2df' })
hi(0, 'MiniStatuslineFilename', { bg = '#181826', fg = '#cdd6f5' })
hi(0, 'MiniStatuslineInactive', { bg = '#181826', fg = '#89b4fb' })
hi(0, 'MiniStatuslineModeCommand', { bg = colors.red, bold = true, fg = colors.background })
hi(0, 'MiniStatuslineModeInsert', { bg = '#a6e3a2', bold = true, fg = colors.background })
hi(0, 'MiniStatuslineModeNormal', { bg = '#89b4fb', bold = true, fg = '#181826' })
hi(0, 'MiniStatuslineModeOther', { bg = '#94e2d6', bold = true, fg = colors.background })
hi(0, 'MiniStatuslineModeReplace', { bg = colors.orange, bold = true, fg = colors.background })
hi(0, 'MiniStatuslineModeVisual', { bg = '#cba6f8', bold = true, fg = colors.background })
hi(0, 'MiniSurround', { bg = '#f5c2e8', fg = '#45475b' })
hi(0, 'MiniTablineCurrent',
	{ bg = colors.background, bold = true, fg = '#cdd6f5', italic = true, sp = '#f38ba9', underline = true })
hi(0, 'MiniTablineFill', { bg = colors.background })
hi(0, 'MiniTablineHidden', { bg = '#181826', fg = '#cdd6f5' })
hi(0, 'MiniTablineModifiedCurrent', { bold = true, fg = '#f38ba9', italic = true })
hi(0, 'MiniTablineModifiedHidden', { fg = '#f38ba9' })
hi(0, 'MiniTablineModifiedVisible', { fg = '#f38ba9' })
hi(0, 'MiniTablineTabpagesection', { bg = colors.background, fg = '#45475b' })
hi(0, 'MiniTestEmphasis', { bold = true })
hi(0, 'MiniTestFail', { bold = true, fg = '#f38ba9' })
hi(0, 'MiniTestPass', { bold = true, fg = '#a6e3a2' })
hi(0, 'MiniTrailspace', { bg = '#f38ba9' })
hi(0, 'ModeMsg', { bold = true, fg = '#cdd6f5' })
hi(0, 'MoreMsg', { fg = '#89b4fb' })
hi(0, 'MsgSeparator', {})
hi(0, 'MultiCursorCursor', { reverse = true })
hi(0, 'MultiCursorDisabledCursor', { reverse = true })
hi(0, 'NeoTreeDimText', { fg = '#7f849d' })
hi(0, 'NeoTreeDirectoryIcon', { fg = '#89b4fb' })
hi(0, 'NeoTreeDirectoryName', { fg = '#89b4fb' })
hi(0, 'NeoTreeExpander', { fg = '#6c7087' })
hi(0, 'NeoTreeFileNameOpened', { fg = '#f5c2e8' })
hi(0, 'NeoTreeFilterTerm', { bold = true, fg = '#a6e3a2' })
hi(0, 'NeoTreeFloatBorder', { link = 'FloatBorder' })
hi(0, 'NeoTreeFloatTitle', { link = 'FloatTitle' })
hi(0, 'NeoTreeGitAdded', { fg = '#a6e3a2' })
hi(0, 'NeoTreeGitConflict', { fg = '#f38ba9' })
hi(0, 'NeoTreeGitDeleted', { fg = '#f38ba9' })
hi(0, 'NeoTreeGitIgnored', { fg = '#6c7087' })
hi(0, 'NeoTreeGitModified', { fg = '#f9e2b0' })
hi(0, 'NeoTreeGitStaged', { fg = '#a6e3a2' })
hi(0, 'NeoTreeGitUnstaged', { fg = '#f38ba9' })
hi(0, 'NeoTreeGitUntracked', { fg = '#cba6f8' })
hi(0, 'NeoTreeIndentMarker', { fg = '#6c7087' })
hi(0, 'NeoTreeModified', { fg = '#fab388' })
hi(0, 'NeoTreeNormal', { bg = '#181826', fg = '#cdd6f5' })
hi(0, 'NeoTreeNormalNC', { bg = '#181826', fg = '#cdd6f5' })
hi(0, 'NeoTreeRootName', { bold = true, fg = '#89b4fb' })
hi(0, 'NeoTreeStatusLineNC', { bg = '#181826', fg = '#181826' })
hi(0, 'NeoTreeSymbolicLinkTarget', { fg = '#f5c2e8' })
hi(0, 'NeoTreeTabActive', { bg = '#181826', bold = true, fg = '#b4beff' })
hi(0, 'NeoTreeTabInactive', { bg = colors.background, fg = '#6c7087' })
hi(0, 'NeoTreeTabSeparatorActive', { bg = '#181826', fg = '#181826' })
hi(0, 'NeoTreeTabSeparatorInactive', { bg = colors.background, fg = '#1e1e2f' })
hi(0, 'NeoTreeTitleBar', { bg = '#89b4fb', fg = '#181826' })
hi(0, 'NeoTreeVertSplit', { bg = colors.background, fg = '#1e1e2f' })
hi(0, 'NeoTreeWinSeparator', { bg = colors.background, fg = '#1e1e2f' })
hi(0, 'NeogitBranch', { bold = true, fg = '#fab388' })
hi(0, 'NeogitChangeAdded', { bold = true, fg = '#a6e3a2' })
hi(0, 'NeogitChangeBothModified', { bold = true, fg = '#f9e2b0' })
hi(0, 'NeogitChangeCopied', { bold = true, fg = '#f5c2e8' })
hi(0, 'NeogitChangeDeleted', { bold = true, fg = '#f38ba9' })
hi(0, 'NeogitChangeModified', { bold = true, fg = '#89b4fb' })
hi(0, 'NeogitChangeNewFile', { bold = true, fg = '#a6e3a2' })
hi(0, 'NeogitChangeRenamed', { bold = true, fg = '#cba6f8' })
hi(0, 'NeogitChangeUpdated', { bold = true, fg = '#fab388' })
hi(0, 'NeogitCommitViewHeader', { bg = '#3e4b6c', fg = '#97bbfa' })
hi(0, 'NeogitDiffAdd', { bg = '#2b313a', fg = '#8bbc8b' })
hi(0, 'NeogitDiffAddHighlight', { bg = '#4d6257', fg = '#ace1ae' })
hi(0, 'NeogitDiffContext', { bg = colors.background })
hi(0, 'NeogitDiffContextHighlight', { bg = '#313245' })
hi(0, 'NeogitDiffDelete', { bg = '#32283b', fg = '#c87591' })
hi(0, 'NeogitDiffDeleteHighlight', { bg = '#674459', fg = '#ed96b4' })
hi(0, 'NeogitDiffHeader', { bg = colors.background, bold = true, fg = '#89b4fb' })
hi(0, 'NeogitDiffHeaderHighlight', { bg = colors.background, bold = true, fg = '#fab388' })
hi(0, 'NeogitFilePath', { fg = '#89b4fb', italic = true })
hi(0, 'NeogitGraphBlue', { fg = '#89b4fb' })
hi(0, 'NeogitGraphBoldBlue', { bold = true, fg = '#89b4fb' })
hi(0, 'NeogitGraphBoldCyan', { bold = true, fg = '#89b4fb' })
hi(0, 'NeogitGraphBoldGray', { bold = true, fg = '#bac2df' })
hi(0, 'NeogitGraphBoldGreen', { bold = true, fg = '#a6e3a2' })
hi(0, 'NeogitGraphBoldPurple', { bold = true, fg = '#b4beff' })
hi(0, 'NeogitGraphBoldRed', { bold = true, fg = '#f38ba9' })
hi(0, 'NeogitGraphBoldWhite', { bold = true })
hi(0, 'NeogitGraphBoldYellow', { bold = true, fg = '#f9e2b0' })
hi(0, 'NeogitGraphCyan', { fg = '#89b4fb' })
hi(0, 'NeogitGraphGray', { fg = '#bac2df' })
hi(0, 'NeogitGraphGreen', { fg = '#a6e3a2' })
hi(0, 'NeogitGraphOrange', { fg = '#fab388' })
hi(0, 'NeogitGraphPurple', { fg = '#b4beff' })
hi(0, 'NeogitGraphRed', { fg = '#f38ba9' })
hi(0, 'NeogitGraphWhite', { fg = colors.background })
hi(0, 'NeogitGraphYellow', { fg = '#f9e2b0' })
hi(0, 'NeogitHunkHeader', { bg = '#282c42', fg = '#546995' })
hi(0, 'NeogitHunkHeaderHighlight', { bg = '#353e5b', fg = '#89b4fb' })
hi(0, 'NeogitNotificationError', { fg = '#f38ba9' })
hi(0, 'NeogitNotificationInfo', { fg = '#89b4fb' })
hi(0, 'NeogitNotificationWarning', { fg = '#f9e2b0' })
hi(0, 'NeogitObjectId', { link = 'Comment' })
hi(0, 'NeogitPopupActionKey', { fg = '#b4beff' })
hi(0, 'NeogitPopupBold', { bold = true })
hi(0, 'NeogitPopupConfigKey', { fg = '#b4beff' })
hi(0, 'NeogitPopupOptionKey', { fg = '#b4beff' })
hi(0, 'NeogitPopupSwitchKey', { fg = '#b4beff' })
hi(0, 'NeogitRebaseDone', { link = 'Comment' })
hi(0, 'NeogitRebasing', { bold = true, fg = '#cba6f8' })
hi(0, 'NeogitRecentcommits', { bold = true, fg = '#cba6f8' })
hi(0, 'NeogitRemote', { bold = true, fg = '#a6e3a2' })
hi(0, 'NeogitSectionHeader', { bold = true, fg = '#cba6f8' })
hi(0, 'NeogitStagedchanges', { bold = true, fg = '#cba6f8' })
hi(0, 'NeogitStash', { link = 'Comment' })
hi(0, 'NeogitStashes', { bold = true, fg = '#cba6f8' })
hi(0, 'NeogitTagDistance', { fg = '#89b4fb' })
hi(0, 'NeogitTagName', { fg = '#f9e2b0' })
hi(0, 'NeogitUnmergedInto', { link = 'Function' })
hi(0, 'NeogitUnmergedchanges', { bold = true, fg = '#cba6f8' })
hi(0, 'NeogitUnpulledFrom', { link = 'Function' })
hi(0, 'NeogitUnpulledchanges', { bold = true, fg = '#cba6f8' })
hi(0, 'NeogitUnpushedTo', { bold = true, fg = '#b4beff' })
hi(0, 'NeogitUnstagedchanges', { bold = true, fg = '#cba6f8' })
hi(0, 'NeogitUntrackedfiles', { bold = true, fg = '#cba6f8' })
hi(0, 'NeogitWinSeparator', { link = 'WinSeparator' })
hi(0, 'NonText', { fg = '#6c7087' })
hi(0, 'Normal', { bg = colors.background, fg = '#cdd6f5' })
hi(0, 'NormalFloat', { bg = '#181826', fg = '#cdd6f5' })
hi(0, 'NormalNC', { bg = colors.background, fg = '#cdd6f5' })
hi(0, 'NormalSB', { bg = '#11111c', fg = '#cdd6f5' })
hi(0, 'Number', { fg = '#fab388' })
hi(0, 'NvimTreeEmptyFolderName', { fg = '#89b4fb' })
hi(0, 'NvimTreeFolderIcon', { fg = '#89b4fb' })
hi(0, 'NvimTreeFolderName', { fg = '#89b4fb' })
hi(0, 'NvimTreeGitDeleted', { fg = '#f38ba9' })
hi(0, 'NvimTreeGitDirty', { fg = '#f9e2b0' })
hi(0, 'NvimTreeGitNew', { fg = '#89b4fb' })
hi(0, 'NvimTreeImageFile', { fg = '#cdd6f5' })
hi(0, 'NvimTreeIndentMarker', { fg = '#6c7087' })
hi(0, 'NvimTreeNormal', { bg = '#181826', fg = '#cdd6f5' })
hi(0, 'NvimTreeOpenedFile', { fg = '#f5c2e8' })
hi(0, 'NvimTreeOpenedFolderName', { fg = '#89b4fb' })
hi(0, 'NvimTreeRootFolder', { bold = true, fg = '#b4beff' })
hi(0, 'NvimTreeSpecialFile', { fg = '#f2cdce' })
hi(0, 'NvimTreeStatuslineNc', { bg = '#181826', fg = '#181826' })
hi(0, 'NvimTreeSymlink', { fg = '#f5c2e8' })
hi(0, 'NvimTreeWinSeparator', { bg = colors.background, fg = '#11111c' })
hi(0, 'Operator', { fg = colors.cyan })
hi(0, 'Pmenu', { bg = '#2b2b3d', fg = '#9399b3' })
hi(0, 'PmenuExtra', { fg = '#6c7087' })
hi(0, 'PmenuExtraSel', { fg = '#6c7087' })
hi(0, 'PmenuSbar', { bg = '#45475b' })
hi(0, 'PmenuSel', { bg = '#45475b', bold = true })
hi(0, 'PmenuThumb', { bg = '#6c7087' })
hi(0, 'PreProc', { fg = '#f5c2e8' })
hi(0, 'Question', { fg = '#89b4fb' })
hi(0, 'QuickFixLine', { bg = '#45475b', bold = true })

local rainbow_colors = {
	--DEPRECATE: these are prof's original colors
	--'#89b4fb',
	--'#94e2d6',
	--'#a6e3a2',
	--'#fab388',
	--'#f38ba9',
	--'#cba6f8',
	--'#f9e2b0',

	-- shades of grey, generated procedurally {{{1
	'#cccccc',
	'#b3b3b3',
	'#999999',
	'#808080',
	'#666666',
	'#4c4c4c',
	'#333333',
	--,}}}1
}

hi(0, 'RainbowRed', { fg = rainbow_colors[1] })
hi(0, 'RainbowYellow', { fg = rainbow_colors[2] })
hi(0, 'RainbowBlue', { fg = rainbow_colors[3] })
hi(0, 'RainbowOrange', { fg = rainbow_colors[4] })
hi(0, 'RainbowGreen', { fg = rainbow_colors[5] })
hi(0, 'RainbowViolet', { fg = rainbow_colors[6] })
hi(0, 'RainbowCyan', { fg = rainbow_colors[7] })
hi(0, 'RainbowDelimiterRed', { fg = rainbow_colors[1] })
hi(0, 'RainbowDelimiterYellow', { fg = rainbow_colors[2] })
hi(0, 'RainbowDelimiterBlue', { fg = rainbow_colors[3] })
hi(0, 'RainbowDelimiterOrange', { fg = rainbow_colors[4] })
hi(0, 'RainbowDelimiterGreen', { fg = rainbow_colors[5] })
hi(0, 'RainbowDelimiterViolet', { fg = rainbow_colors[6] })
hi(0, 'RainbowDelimiterCyan', { fg = rainbow_colors[7] })

hi(0, 'RenderMarkdownBullet', { fg = '#89dcec' })
hi(0, 'RenderMarkdownCode', { bg = '#181826' })
hi(0, 'RenderMarkdownCodeInline', { bg = '#313245' })
hi(0, 'RenderMarkdownError', { fg = '#f38ba9' })
hi(0, 'RenderMarkdownH1', { fg = '#f38ba9' })
hi(0, 'RenderMarkdownH1Bg', { bg = '#32283b' })
hi(0, 'RenderMarkdownH2', { fg = '#fab388' })
hi(0, 'RenderMarkdownH2Bg', { bg = '#332c37' })
hi(0, 'RenderMarkdownH3', { fg = '#f9e2b0' })
hi(0, 'RenderMarkdownH3Bg', { bg = '#33313b' })
hi(0, 'RenderMarkdownH4', { fg = '#a6e3a2' })
hi(0, 'RenderMarkdownH4Bg', { bg = '#2b313a' })
hi(0, 'RenderMarkdownH5', { fg = '#74c7ed' })
hi(0, 'RenderMarkdownH5Bg', { bg = '#262e41' })
hi(0, 'RenderMarkdownH6', { fg = '#b4beff' })
hi(0, 'RenderMarkdownH6Bg', { bg = '#2c2d43' })
hi(0, 'RenderMarkdownHint', { fg = '#94e2d6' })
hi(0, 'RenderMarkdownInfo', { fg = '#89dcec' })
hi(0, 'RenderMarkdownSuccess', { fg = '#a6e3a2' })
hi(0, 'RenderMarkdownTableHead', { fg = '#89b4fb' })
hi(0, 'RenderMarkdownTableRow', { fg = '#b4beff' })
hi(0, 'RenderMarkdownWarn', { fg = '#f9e2b0' })
hi(0, 'Repeat', { fg = '#cba6f8' })
hi(0, 'Search', { bg = '#3e5768', fg = '#cdd6f5' })
hi(0, 'SignColumn', { fg = '#45475b' })
hi(0, 'SignColumnSB', { bg = '#11111c', fg = '#45475b' })
hi(0, 'Special', { fg = '#f5c2e8' })
hi(0, 'SpecialKey', { link = 'NonText' })
hi(0, 'SpellBad', { sp = '#f38ba9', undercurl = true })
hi(0, 'SpellCap', { sp = '#f9e2b0', undercurl = true })
hi(0, 'SpellLocal', { sp = '#89b4fb', undercurl = true })
hi(0, 'SpellRare', { sp = '#a6e3a2', undercurl = true })
hi(0, 'Statement', { fg = '#cba6f8' })
hi(0, 'StatusLine', { bg = '#181826', fg = '#cdd6f5' })
hi(0, 'StatusLineNC', { bg = '#181826', fg = '#45475b' })
hi(0, 'StorageClass', { fg = '#f9e2b0' })
hi(0, 'String', { fg = '#a6e3a2' })
hi(0, 'Structure', { fg = '#f9e2b0' })
hi(0, 'Substitute', { bg = '#45475b', fg = '#f5c2e8' })
hi(0, 'TabLine', { bg = '#11111c', fg = '#6c7087' })
hi(0, 'TabLineFill', { bg = '#181826' })
hi(0, 'TabLineSel', { link = 'Normal' })
hi(0, 'Tag', { bold = true, fg = '#b4beff' })
hi(0, 'TelescopeBorder', { link = 'FloatBorder' })
hi(0, 'TelescopeMatching', { fg = '#89b4fb' })
hi(0, 'TelescopeSelection', { bg = '#313245', bold = true, fg = '#cdd6f5' })
hi(0, 'TelescopeSelectionCaret', { fg = '#f2cdce' })
hi(0, 'TermCursor', { bg = '#f5e0dd', fg = colors.background })
hi(0, 'TermCursorNC', { bg = '#9399b3', fg = colors.background })
hi(0, 'Title', { bold = true, fg = '#89b4fb' })
hi(0, 'Todo', { bg = '#f2cdce', bold = true, fg = colors.background })
hi(0, 'TreesitterContextBottom', { sp = '#313245', underline = true })
hi(0, 'TreesitterContextLineNumber', { bg = '#181826', fg = '#45475b' })
hi(0, 'Type', { fg = '#f9e2b0' })
hi(0, 'UfoFoldedEllipsis', { bg = '#89b4fb', fg = '#11111c' })
hi(0, 'UfoFoldedFg', { fg = '#b4beff' })
hi(0, 'VertSplit', { fg = '#11111c' })
hi(0, 'Visual', { bg = '#45475b', bold = true })
hi(0, 'VisualNOS', { bg = '#45475b', bold = true })
hi(0, 'WarningMsg', { fg = '#f9e2b0' })
hi(0, 'Whitespace', { fg = '#45475b' })
hi(0, 'WildMenu', { bg = '#6c7087' })
hi(0, 'WinBar', { fg = '#f5e0dd' })
hi(0, 'WinBarNC', { link = 'WinBar' })
hi(0, 'WinSeparator', { fg = '#11111c' })
hi(0, 'ZenBg', { bg = '#1c1c2c', fg = '#1c1c2c' })
hi(0, 'csvCol0', { fg = '#f38ba9' })
hi(0, 'csvCol1', { fg = '#fab388' })
hi(0, 'csvCol2', { fg = '#f9e2b0' })
hi(0, 'csvCol3', { fg = '#a6e3a2' })
hi(0, 'csvCol4', { fg = '#89dcec' })
hi(0, 'csvCol5', { fg = '#89b4fb' })
hi(0, 'csvCol6', { fg = '#b4beff' })
hi(0, 'csvCol7', { fg = '#cba6f8' })
hi(0, 'csvCol8', { fg = '#f5c2e8' })
hi(0, 'debugBreakpoint', { bg = colors.background, fg = '#6c7087' })
hi(0, 'debugPC', { bg = '#11111c' })
hi(0, 'diffLine', { fg = '#6c7087' })
hi(0, 'diffNewFile', { fg = '#fab388' })
hi(0, 'diffOldFile', { fg = '#f9e2b0' })
hi(0, 'gitcommitSummary', { fg = '#f5e0dd', italic = true })
hi(0, 'healthError', { fg = '#f38ba9' })
hi(0, 'healthSuccess', { fg = '#94e2d6' })
hi(0, 'healthWarning', { fg = '#f9e2b0' })
hi(0, 'htmlH1', { bold = true, fg = '#f5c2e8' })
hi(0, 'htmlH2', { bold = true, fg = '#89b4fb' })
hi(0, 'illuminatedCurWord', { bg = '#45475b' })
hi(0, 'illuminatedWord', { bg = '#45475b' })
hi(0, 'lCursor', { bg = '#f5e0dd', fg = colors.background })
hi(0, 'markdownCode', { fg = '#f2cdce' })
hi(0, 'markdownCodeBlock', { fg = '#f2cdce' })
hi(0, 'markdownH1', { link = 'rainbow1' })
hi(0, 'markdownH2', { link = 'rainbow2' })
hi(0, 'markdownH3', { link = 'rainbow3' })
hi(0, 'markdownH4', { link = 'rainbow4' })
hi(0, 'markdownH5', { link = 'rainbow5' })
hi(0, 'markdownH6', { link = 'rainbow6' })
hi(0, 'markdownHeadingDelimiter', { bold = true, fg = '#fab388' })
hi(0, 'markdownLinkText', { fg = '#89b4fb', underline = true })
hi(0, 'mkdCodeDelimiter', { bg = colors.background, fg = '#cdd6f5' })
hi(0, 'mkdCodeEnd', { bold = true, fg = '#f2cdce' })
hi(0, 'mkdCodeStart', { bold = true, fg = '#f2cdce' })
hi(0, 'qfFileName', { fg = '#89b4fb' })
hi(0, 'qfLineNr', { fg = '#f9e2b0' })
hi(0, 'rainbow1', { fg = '#f38ba9' })
hi(0, 'rainbow2', { fg = '#fab388' })
hi(0, 'rainbow3', { fg = '#f9e2b0' })
hi(0, 'rainbow4', { fg = '#a6e3a2' })
hi(0, 'rainbow5', { fg = '#74c7ed' })
hi(0, 'rainbow6', { fg = '#b4beff' })
hi(0, 'zshKSHFunction', { link = 'Function' })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = '#101012'
g.terminal_color_1 = '#de5d68'
g.terminal_color_2 = '#8fb573'
g.terminal_color_3 = '#dbb671'
g.terminal_color_4 = '#57a5e5'
g.terminal_color_5 = '#bb70d2'
g.terminal_color_6 = '#51a8b3'
g.terminal_color_7 = '#a7aab0'
g.terminal_color_8 = '#5a5b5e'
g.terminal_color_9 = '#de5d68'
g.terminal_color_10 = '#8fb573'
g.terminal_color_11 = '#dbb671'
g.terminal_color_12 = '#57a5e5'
g.terminal_color_13 = '#bb70d2'
g.terminal_color_14 = '#51a8b3'
g.terminal_color_15 = '#a7aab0'
