{ lib }:
let
  sshAuthorizedKeys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEJA6PHRdXNysN/q8yYid3Vp3miFBB7a1441lOEHeOoZ valeratrades@gmail.com"
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIz2m3ZyGSMog5x8GaboPfZqsuNqUO6E/031wks5eicU root@v-laptop"
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDXayiFOnCRwOk3wKXkTOi3ix6x8t8v4t2fgTqalIlki ev"
  ];
in
{
  # # useful to have these default for servers. When sharing the config with someone else for use as main desktop, should just be overriding.
  # generated by `mkpasswd -m scrypt`
  #TODO!: \
  #initialHashedPassword = "$7$CU..../....KDvTIXqLTXpmCaoUy2yC9.$145eM358b7Q0sRXgEBvxctd5EAuEEdao57LmZjc05D.";
  # Public Keys that can be used to login to all my PCs, Macbooks, and servers.
  #
  # Since its authority is so large, we must strengthen its security:
  # 1. The corresponding private key must be:
  #    1. Generated locally on every trusted client via:
  #      ```bash
  #      # KDF: bcrypt with 256 rounds, takes 2s on Apple M2):
  #      # Passphrase: digits + letters + symbols, 12+ chars
  #      ssh-keygen -t ed25519 -a 256 -C "ryan@xxx" -f ~/.ssh/xxx`
  #      ```
  #    2. Never leave the device and never sent over the network.
  # 2. Or just use hardware security keys like Yubikey/CanoKey.

  #HACK: there are better ways to do this and especially to ensure that the set of args is unifyied for every user, but can't be bothered.
  valera = {
    inherit sshAuthorizedKeys;
    # Keys an *agent* logs in with, kept out of sshAuthorizedKeys because that list
    # also seeds root on the rpi5. Private half lives in sops
    # (secrets/users/v -> rpi5_valera_ssh_key), read by hosts/rpi5-valera.
    agentKeys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILkOLH+R/DDw/JH1dFok3/YzAbmQbqe2Kq7feNPsuVqv valera@rpi5 (openclaw)"
    ];
    username = "v";
    userFullName = "Valera";
    desktopHostName = "v-laptop";
		symlinkConfigs = true;
    defaultUsername = "valeratrades";
    defaultUserEmail = "v79166789533@gmail.com";
    masterUserEmail = "valeratrades@gmail.com";
    wakeTime = "07:10"; # matches system time, (my system time is utc)
    fontSize = 10;
		kbd = "ansi";
		sccache = true;
		disableNvidia = false;  # set to true to use AMD iGPU only (better battery, fewer driver issues)
		gpuAcceleration = false;  # forced Firefox GPU rendering (webrender compositor + dmabuf + gpu-process). Off: runs hot on this chassis.
		clickhouse = false;
		# The agent moved to the rpi5 (hosts/rpi5-valera), which is always on. It cannot
		# run in both places: a Telegram bot token admits exactly one getUpdates
		# consumer, and openclaw_workspace — the agent's memory, which it commits to —
		# admits one writer. Flipping this back means turning the rpi5 one off first.
		openclaw = false;
		default_s_inactive_to_retire = 1200; # idle LSP servers paged out to swap after this many seconds (20m)
		# Hearing-safety: max dB SPL per headphone, keyed by PipeWire node.description.
		# Mapped to a digital limiter via the model's calibration in
		# os/nixos/desktop/services/headphone-calibration.nix. 85 dB = OSHA 8h-safe.
		sound.device_limiters = { "WH-1000XM4" = 85; };
  };
  maria = {
    inherit sshAuthorizedKeys;
    agentKeys = [ ];
    username = "m";
    userFullName = "Maria";
    desktopHostName = "m-laptop";
		symlinkConfigs = false;
    defaultUsername = "sakhmasha";
    defaultUserEmail = "m79160164445@gmail.com";
    masterUserEmail = "m79160164445@gmail.com";
    wakeTime = "06:00";
    fontSize = 11;
		kbd = "iso";
		gpuAcceleration = true;
		clickhouse = true;
		openclaw = false;
		default_s_inactive_to_retire = 1200;
    };
  timur = {
    inherit sshAuthorizedKeys;
    agentKeys = [ ];
    username = "t";
    userFullName = "Timur";
    desktopHostName = "t-laptop";
		symlinkConfigs = false;
    defaultUsername = "codertima";
    defaultUserEmail = "codertima@gmail.com";
    masterUserEmail = "codertima@gmail.com";
    wakeTime = "05:00";
    fontSize = 12;
		kbd = "ansi";
		gpuAcceleration = true;
		clickhouse = true;
		openclaw = false;
		default_s_inactive_to_retire = 1200;
  };
  #

  ports = import ./ports.nix;

  #TODO: networking. Albeit right now it doesn't have much merrit, as I don't have even one server with nix. Just people's configs.
  #networking = import ./networking.nix {inherit lib;};
}
