source (dirname (status --current-filename))/cargo.fish
source (dirname (status --current-filename))/direnv.fish
source (dirname (status --current-filename))/git.fish
source (dirname (status --current-filename))/nix/mod.fish
source (dirname (status --current-filename))/music.fish
source (dirname (status --current-filename))/go.fish
source (dirname (status --current-filename))/nvim.fish
source (dirname (status --current-filename))/ssh.fish
source (dirname (status --current-filename))/swappy.fish
source (dirname (status --current-filename))/tg.fish
source (dirname (status --current-filename))/tmux.fish
source (dirname (status --current-filename))/zathura.fish
source (dirname (status --current-filename))/uv.fish
source (dirname (status --current-filename))/llm.fish
