alias tga="tg send -c alerts >/dev/null"
alias tgf="tg send -c far-fetched >/dev/null"
alias tgg="tg send -c general >/dev/null"
alias tgj="tg send -c journal >/dev/null"
alias tgl="tg send -c learning >/dev/null"
alias tgm="tg send -c making >/dev/null"
alias tgt="tg send -c math >/dev/null"
alias tgi="tg send -c tooling >/dev/null"
alias tgr="tg send -c trading >/dev/null"

alias tgo="tg open"
