telegram_token_main: ENC[AES256_GCM,data:R/F5MaRIFYkdK3dA3QLoRZOoYhNUXDbh4jWKwjYwTRAwgnMdeOPZ6sImkD3G8w==,iv:vl1Bz1DMb2Hs8gupy8qHgY6ghBrc8Bp4sxXTA4ETAy8=,tag:buRaLzjvptC38A2IRbRREA==,type:str]
hello: ENC[AES256_GCM,data:b8CidxrU5LDcEv/IrFpf/LlT0cYayY4lefh17/zcTjnT9Kpu5DJ/EmPqKrBUJQ==,iv:hcSA88xLufNqHASVY38hqGyD7hlgJ59Cz4OxHyxFFIQ=,tag:oibTS1DGd8zJIssd+kezFQ==,type:str]
example_key: ENC[AES256_GCM,data:e8WMuhW0IJrO5EKnRw==,iv:LX3iEQ2VCacl33KskT93aXGzSky0gNTKWiLfGXZZwXg=,tag:QBUwVkyNIDOpuzatkE1qrg==,type:str]
#ENC[AES256_GCM,data:GZIM7R++c891/c0YXkEs7w==,iv:5D6C/G2+GZOF4lbuK1/zoEPWuvJW/yah3GNgNEZDkmY=,tag:5fePz63txb7Ojl8cohdpDw==,type:comment]
example_array:
    - ENC[AES256_GCM,data:GpSbKofacN46vekIs5E=,iv:wvnhJRYMfShBmtwrtoCInMAAI1joEwCc18jagn115kg=,tag:JcGNec59Gbp385H9UG5HXw==,type:str]
    - ENC[AES256_GCM,data:OghUrxAt8xfw/v1NQIY=,iv:/dPFweBaa6vSqrpa9eUjhSEiPICf2BlizuiXimw46JE=,tag:n6QIYpfbQ6hK1o2E3YsWrw==,type:str]
example_number: ENC[AES256_GCM,data:koYfWxeU5KbR7Q==,iv:Z+ZTgxUMt0C78yIaWhSui4zgdQx2Nxlj7KgGAdAoVN0=,tag:ZpogwDgGkaK6O1eqDxQn1w==,type:float]
example_booleans:
    - ENC[AES256_GCM,data:gYNIDA==,iv:hUn8M0lsmqTWqpfgu6tfOiUkXkbUNXAy5wHDCDYTMIA=,tag:qIhUXr6SbvwDhjzxf85IoA==,type:bool]
    - ENC[AES256_GCM,data:zekoB7U=,iv:RtB4GT9IvsmMlVOZ/fvG6dE6YBvQPc5lAf14T0BOMrQ=,tag:5AFCDGga0nbLzng7EH0j0g==,type:bool]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q750njxr0gnlftxygvfrd4vschrgmj532zat45ycx6fkek8zvp4s9pgqp7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyYjBodDd1a3NjNVlxTE1i
            RE9BaE5XcGdMZmdONHVRdjRIWEFhdlhTZmhBCnM1YUNkeGloNjhyd2J3R3NHc1dr
            VERyemVqR1o5Zmc2QzIxL1EvZ0tld2sKLS0tIEQwV3ZsSmZwdE1XYnM4R215TEZm
            dDVDOWpFeDRIM1NKYU5UWUZSdkM5Z28KmB8Oo05pN16iBeYKx5ZkwkCQvihnjg+K
            va46+8EbM3Qu8f/fFaX0bSFGXh6ZebZUnLuO/3qbsBAGTLZ2lFyLgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-25T18:40:37Z"
    mac: ENC[AES256_GCM,data:FXEB3aRsHWy5jS2HWQYaT8xypHXgPnydr6Euq0E8wCsupcDPYYhKJTtK8FIZpxVPst+yWTsmeaho7ECcHiEdfYWy4QLqdquYqPtEGpmOQNGDYz+otxYwFfquGDLAOyf1JXPEf9pFGWN1LhQgU1iCO9N5JxzV5lypV+Xr/df2pHY=,iv:mcV5aAP4CavsYddGzdYz96o/BZeyvpU3weS2EwUrWT8=,tag:rmSAUT9qFUr3ZBNvhlYXCw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
